name: lo_form
version: 0.4.0
description: Low-code and lightweight Flutter library for forms' state management.
repository: https://github.com/YoussefRaafatNasry/lo_form
homepage: https://YoussefRaafatNasry.github.io/lo_form
documentation: https://docs.page/YoussefRaafatNasry/lo_form

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  assets:
    # Used in website to load package info
    - pubspec.yaml
